apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-go
  labels: {app: hello-go}
spec:
  replicas: 1
  template:
    metadata: {labels: {app: hello-go}}
    spec:
      containers:
      - name: news
        image: gcr.io/my_gcr_project/hello-go:latest
        command:
        ports:
          - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-go
spec:
  type: LoadBalancer
  selector:
    app: hello-go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080